### ISSUE TITLE
Home Person is selected when the view is initially selected

### ISSUE THREAD

**Issue by DaveSch-gramps** [cdhorn/profileview#40]
In the most recent updates (13 July), when the view is initially selected, the home person and not the active person is the person displayed. This is a change where the active person was always displayed. I reinstalled an older version (29 June) from my backups to confirm the change of behavior.

**Comment by cdhorn** [comment]
Likely result of using the enhanced navigation class. Ideally it should probably resume on the object being viewed as well if it was not a person. Thanks for pointing that out.

**Comment by DaveSch-gramps** [comment]
This active/home person issue occurs in the combined view. I thought you had solved it and could share the fix. The addon graph views do not seem to have this issue.

**Comment by cdhorn** [comment]
Yes that makes sense. The Navigation class used in Gramps core was modified for the Combined view and I have switched back to using an iteration of that one to support navigating across different objects. That was what I first used when I converted my Gramplet to a view but I thought using the Gramps core version would simplify things. But it lacks the functionality that Nick added which I have realized I needed so that was a mistake and I have pivoted back to using his framework. 

I will likely fix it by stashing the current tree/object in the ini file. A number of the config options for the view are global but a number are now indexed by tree.

**Comment by cdhorn** [comment]
Think this mostly works with commit 6dfb2fa7e5c29dd8cbac102b30f3ff7cdda20e90 now.

The problem is the History class in the enhanced NavigationView class always reset it to the default person when the history was cleared and the history does not appear to be saved across sessions but I didn't dig too deep. I had to disable that behaviour and make some other hackish changes to make it work for now.
