### ISSUE TITLE
Enhancement: Reset Page default button confirmation & extension

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/profileview#43]
Thank you for adding the Reset Page Defaults.

Could you add a dialog which confirms? If the confirmation asks whether the user wants to clear the current tab or all custom setting in the Profile view, then the feature could be reusable on all the tabs. You could just pass a Tab page number.

In this case, the label could also be simplified to "Reset", moved to be on the bottombar beside the 'Cancel' button and use a standard translation string.

**Comment by cdhorn** [comment]
At moment it only resets options on the current page, not globally. It's a half measure, I didn't close the issue yet as I did not sort out resetting the color schemas or provide a global reset all yet.

The idea of a dialog to confirm and allow them to pick that page or global is a good approach.

To add the reset button to the bottombar I'm pretty sure I'd need to change code in Gramps core as the generated panels just plug into the existing framework.

Take note that the configuration options dialog is generated based on page view. So on person page it is person options, on source page and event page they are the same but different sets of options. I broke things out into various namespaces which you'll notice if you look at page_options.py or the .ini file for the plugin.  Yeah there will be a few hundred when all is said and done I suppose.

**Comment by cdhorn** [comment]
Commit 81f3b85dded17313c8fd9b47310361451b434767 does the following:

1. Refactored options name space, object frames now have one set of options if active in the header and another if in a group.
2. Refactored plugin configuration panels, all options are now in one place.
3. Fold layout editor into the configuration dialog, no longer a separate window and method to access.
4. Add warning dialog on reset to defaults, with a checkbox option to reset all options and not just the page.

Note configuration dialog is slow to load because it takes a while to build, resetting all options takes a long time while examining them all to see if any changed and need to be reset, and layout section could be better integrated with the whole.
